name = "Valhelsia 6+"
author = "Tylian + ValhelsiaTeam"
version = "6.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07fa12e7d2211a5d93259ddb50de8e48b487ecb375cfeed97c22df8eb98da6f3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
