name = "Valhelsia 6+"
author = "Tylian + ValhelsiaTeam"
version = "6.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb5394e8284f06845a30ba9b5fb925b43fcc211e2e709eb78ccfebfbcc7c891b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
