name = "Valhelsia 6+"
author = "Tylian + ValhelsiaTeam"
version = "6.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0575b5accdbd08573897a849fa8e90f508ecc58bcb7dfd4c9ca0ebedc4999103"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
